public class Main {
    public static void main(String[] args) {
        System.out.println("ЗАДАЧА №1");
        int sec = 86400;
        byte now = 1;
        var minute = 1440;
        long minuteYear = 525600;
        long secYear = 31536000;
        float weight = (float) 56.1;
        double weight4 = weight * 4;
        String result = String.format("%.1f",weight4);
        System.out.println("В сутках " + sec + " секунд.");
        System.out.println("В сутках " + minute + " минут.");
        System.out.println("В году " + minuteYear + " минут и " + secYear + " секунд.");
        System.out.println("Cейчас в Москве " + now + " час дня.");
        System.out.println("Я вешу " + weight + " кг.");
        System.out.println("Четыре меня это " + result + " кг.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №2");
        double seedEat = (float) 27.12;
        String result1 = String.format("%.2f",seedEat);
        long seed = 987678965549L;
        float seedEat1 = (float) 2.786;
        boolean cat = false;
        int hor = 569;
        int minusHor = -159;
        int cattle = 27897;
        byte kill = 67;
        System.out.println("В среднем одно животное в сутки съедает " + result1 + " кг.");
        System.out.println("За год " + seed + " кг.");
        System.out.println("За 10 часов в среднем съедают " + seedEat1 + " кг.");
        System.out.println("Это " + cat + ", ей не может быть столько лет.");
        System.out.println("На ферме " + hor + " лошадей.");
        System.out.println("Лошадей стало на " + minusHor + " меньше.");
        System.out.println("Всего на ферме " + cattle + " голов скота.");
        System.out.println("За этот год погибло " + kill + " голов.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №3");
        byte lpSchoolchild = 23;
        byte asSchoolchild = 27;
        byte eaSchoolchild = 30;
        byte totalSchoolchild = (byte) (lpSchoolchild + asSchoolchild + eaSchoolchild);
        byte page = (byte) (480 / totalSchoolchild);
        System.out.println("На каждого ученика рассчитано " + page + " листов бумаги.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №4");
        String perf1 = "20 минут";
        String perf2 = "сутки";
        String perf3 = "3 дня";
        String perf4 = "1 месяц";
        byte oneMinut = 16 / 2;
        byte minut1 = 20;
        short minut2 = 24 * 60;
        short minut3 = (short) (minut2 * 3);
        int minut4 = minut2 * 31;
        short performance1 = (short) (minut1 * oneMinut);
        short performance2 = (short) (minut2 * oneMinut);
        int performance3 = minut3 * oneMinut;
        int performance4 = minut4 * oneMinut;
        System.out.println(" За " + perf1 + " машины произвели бутылок - " + performance1 + " штук.");
        System.out.println(" За " + perf2 + " машины произвели бутылок - " + performance2 + " штук.");
        System.out.println(" За " + perf3 + " машины произвели бутылок - " + performance3 + " штук.");
        System.out.println(" За " + perf4 + " машины произвели бутылок - " + performance4 + " штук.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №5");
        short paintAll = 120;
        byte paintWh = 2;
        byte paintBr = 4;
        int all = paintAll / (paintWh + paintBr);
        int allWh = paintWh * all;
        int allBr = paintBr * all;
        System.out.println("В школе, где " + all + " классов, нужно " + allWh + " банок белой краски и " + allBr + " банок коричневой краски.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №6");
        int banana = 5 * 80;
        int milk = 2 * 105;
        int ice = 2 * 100;
        int egg = 4 * 70;
        int allWeight = (banana + milk + ice + egg) / 1000;
        System.out.println( "Вес спорт-завтрака - " + allWeight + " кг.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №7");
        int first = 250;
        int second = 500;
        int allWeight1 = 7 * 1000;
        int weight250 = allWeight1 / first;
        int weight500 = allWeight1 / second;
        int medium = (weight250 + weight500) / 2;
        System.out.println( "При потери 250 грамм в день, спортсмен сбросит 7 кг за " +  weight250 + " дней.");
        System.out.println( "При потери 500 грамм в день, спортсмен сбросит 7 кг за " +  weight500 + " дней.");
        System.out.println("Для похудения потребуется в среднем " + medium + " дней.");
        System.out.println(" ");
        System.out.println("ЗАДАЧА №8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        int mashaBetter = (masha * 10) / 100 + masha;
        int denisBetter = (denis * 10) / 100 + denis;
        int kristinaBetter = (kristina * 10) / 100 + kristina;
        int difference1 = (mashaBetter * 12) - (masha * 12);
        int difference2 = (denisBetter * 12) - (denis * 12);
        int difference3 = (kristinaBetter * 12) - (kristina * 12);
        System.out.println("Маша теперь получает " + mashaBetter + " рублей. Годовой доход вырос на " + difference1 + " рублей.");
        System.out.println("Денис теперь получает " + denisBetter + " рублей. Годовой доход вырос на " + difference2 + " рублей.");
        System.out.println("Кристина теперь получает " + kristinaBetter + " рублей. Годовой доход вырос на " + difference3 + " рублей.");
}
}